tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskMarkDoneView,
    TaskMarkUndoneView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/cteate/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path('task/<int:pk>/mark-done/', TaskMarkDoneView.as_view(), name='task-mark-done'),
    path('task/<int:pk>/mark-undone/', TaskMarkUndoneView.as_view(), name='task-mark-undone'),
]

app_name = "tasks"

to_do/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("tasks.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

tasks/models.py
from django.db import models
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tag = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

tasks/views.py
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse_lazy

from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "tasks/task_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")


class TaskMarkDoneView(generic.View):
    def post(self, request, pk):
        task = Task.objects.get(pk=pk)
        task.is_done = True
        task.save()
        return redirect('tasks:task-list')


class TaskMarkUndoneView(generic.View):
    def post(self, request, pk):
        task = Task.objects.get(pk=pk)
        task.is_done = False
        task.save()
        return redirect('tasks:task-list')


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "tasks/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>{% block title %}Planner{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/includes/confirm_delete_form.html
<form action="" method="post">
  {% csrf_token %}
  <div class="row g-0">
    <div class="col-sm-6 col-md-6">
      <input class="btn btn-secondary" type=button value="Cancel" onClick="history.go(-1);">
    </div>
    <div class="col-sm-6 col-md-6">
      <input type="submit" class="btn btn-danger" value="Yes, delete">
    </div>
  </div>
</form>
  

templates/includes/form.html
{% load crispy_forms_filters %}
<form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Submit">
</form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1>Delete {{ tag.name }} tag</h1>
    Are you sure that you want to delete {{ tag.name }} tag?
  </div>
  {% include 'includes/confirm_delete_form.html' %}
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tag list</h1>
  <p>
    <a class="btn btn-success" href="{% url 'tasks:tag-create' %}">Create new tag</a>
  </p>
  <ul>
    {% if tag_list %}
      {% for tag in tag_list %}
        <li class="row">
          <div class="col">
            {{ tag.name }}
          </div>
          <div class="col">
            <a class="btn btn-primary" href="{% url 'tasks:tag-update' tag.id %}">Update</a>
          </div>
          <div class="col">
            <a class="btn btn-danger" href="{% url 'tasks:tag-delete' tag.id %}">Update</a>
          </div>
        </li>
        <br>

      {% endfor %}
    {% else %}
      <p>There's no tags to display</p>
    {% endif %}

  </ul>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1>Delete {{ task.content }} task</h1>
    Are you sure that you want to delete {{ task.content }} task?
  </div>
  {% include 'includes/confirm_delete_form.html' %}
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Task list</h1>
  <p>
    <a class="btn btn-success" href="{% url 'tasks:task-create' %}">Create new task</a>
  </p>
  {% if task_list %}
    <ul class="list-group col-sm-4">
      {% for task in task_list %}
        <li class="list-group-item">
          {% if task.is_done %}
            <p>
              <strong>Done</strong>
            </p>
          {% endif %}
          <p>{{ task.content }}</p>
          <p><strong>Created at: </strong>
            {{ task.created_at }}</p>
          <p><strong>Deadline: </strong>
            {{ task.deadline }}</p>
          <p><strong>Is done</strong>
            {{ task.is_done }}</p>
          <p><strong>Tags</strong></p>
          <p>Tags: {% for tag in task.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
          {% if not task.is_done %}
            <form method="post" action="{% url 'tasks:task-mark-done' task.pk %}">
              {% csrf_token %}
              <button class="btn btn-success" type="submit">Mark as Done</button>
            </form>
          {% else %}
            <form method="post" action="{% url 'tasks:task-mark-undone' task.pk %}">
              {% csrf_token %}
              <button class="btn btn-secondary" type="submit">Mark as Undone</button>
            </form>
          {% endif %}
          <br>
          <div class="row">
            <div class="col">
              <a class="btn btn-primary" href="{% url 'tasks:task-update' task.id %}">Update</a>
            </div>
            <div class="col">
              <a class="btn btn-danger" href="{% url 'tasks:task-delete' task.id %}">Delete</a>
            </div>
          </div>
        </li>

      {% endfor %}
    </ul>


  {% else %}
    <p>There's no tasks to display</p>
  {% endif %}
{% endblock %}